// Writes docs/i18n-review.md: the interface dictionary (EN | PT) and the exported workbook
// text, for a vocabulary review against the theory documents. Usage: npm run i18n:review
import fs from "node:fs";
import path from "node:path";
import { en } from "../src/i18n/en.ts";
import { pt } from "../src/i18n/pt.ts";

const fx = JSON.parse(fs.readFileSync(path.resolve("../shared-fixtures/export_text.json"), "utf8"));
const esc = (s) => String(s).replaceAll("|", "\\|").replaceAll("\n", " ");
const row = (cells) => `| ${cells.map(esc).join(" | ")} |\n`;
const c = fx.constants;

let o = "# Vocabulary review\n\nGenerated by `npm run i18n:review` from `src/i18n/{en,pt}.ts` and `shared-fixtures/export_text.json`. Regenerate, do not edit by hand.\n\n";
o += "## 1. Exported workbook text (English only, in both interface languages)\n\n### Headers\n\n| Sheet | Columns |\n|---|---|\n";
o += row(["Simulation (radial)", c.sim_header.join(" | ")]);
o += row(["Design", c.design_header.join(" | ")]);
o += row(["Skin", c.skin_header.join(" | ")]);
for (const [k, h] of Object.entries(fx.analysis_headers)) o += row([`Analysis (${k})`, h.join(" | ")]);
o += `\nOther: note column **${c.note_header}**, missing value **${c.not_available}**, figure sheet **${c.chart_summary_sheet}**, length quantity **${c.wormhole_length}** in every sheet.\n\n`;
o += "### Notes (rendered examples)\n\n| Function | Arguments | Text |\n|---|---|---|\n";
for (const n of fx.notes) o += row([n.fn, JSON.stringify(n.args), n.expected]);
o += `\n## 2. Interface dictionary (${Object.keys(en).length} keys)\n\n| Key | English | Português |\n|---|---|---|\n`;
for (const k of Object.keys(en)) o += row([`\`${k}\``, en[k], pt[k]]);

fs.mkdirSync("docs", { recursive: true });
fs.writeFileSync("docs/i18n-review.md", o);
console.log(`docs/i18n-review.md: ${Object.keys(en).length} keys, ${fx.notes.length} note examples`);
